export const meals = [
  {
    name: 'Chicken Alfredo',
    category: 'Pasta',
    price: 1145.18,
    ingredients: [
      'Fettuccine Pasta',
      'Grilled Chicken',
      'Alfredo Sauce',
      'Garlic',
      'Parmesan Cheese',
    ],
    rating: 4.5,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Greek Salad',
    category: 'Salad',
    price: 602.15,
    ingredients: [
      'Romaine Lettuce',
      'Kalamata Olives',
      'Feta Cheese',
      'Cucumber',
      'Tomatoes',
      'Greek Dressing',
    ],
    rating: 4.2,
    type: 'veg',
    image: '',
  },
  {
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    price: 964.61,
    ingredients: [
      'Pizza Dough',
      'Tomato Sauce',
      'Mozzarella Cheese',
      'Pepperoni',
    ],
    rating: 4.7,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Vegetable Curry',
    category: 'Indian',
    price: 857.53,
    ingredients: [
      'Basmati Rice',
      'Mixed Vegetables',
      'Curry Sauce',
      'Coconut Milk',
    ],
    rating: 4.0,
    type: 'veg',
    image: '',
  },
  {
    name: 'Grilled Shrimp Tacos',
    category: 'Mexican',
    price: 1213.88,
    ingredients: [
      'Grilled Shrimp',
      'Corn Tortillas',
      'Cabbage Slaw',
      'Avocado',
      'Lime Crema',
    ],
    rating: 4.6,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Spinach and Feta Stuffed Chicken',
    category: 'Main Course',
    price: 1393.87,
    ingredients: [
      'Chicken Breast',
      'Spinach',
      'Feta Cheese',
      'Sun-Dried Tomatoes',
      'Garlic',
    ],
    rating: 4.8,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Turkey Club Sandwich',
    category: 'Sandwich',
    price: 690.03,
    ingredients: [
      'Turkey',
      'Bacon',
      'Lettuce',
      'Tomato',
      'Mayonnaise',
      'Whole Wheat Bread',
    ],
    rating: 4.1,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Mushroom Risotto',
    category: 'Italian',
    price: 1157.38,
    ingredients: [
      'Arborio Rice',
      'Mushrooms',
      'Onion',
      'White Wine',
      'Parmesan Cheese',
      'Chicken Broth',
    ],
    rating: 4.4,
    type: 'veg',
    image: '',
  },
  {
    name: 'Teriyaki Salmon Bowl',
    category: 'Asian',
    price: 1592.33,
    ingredients: [
      'Salmon Fillet',
      'Teriyaki Sauce',
      'Jasmine Rice',
      'Broccoli',
      'Sesame Seeds',
    ],
    rating: 4.9,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Chocolate Mousse Dessert',
    category: 'Dessert',
    price: 790.16,
    ingredients: [
      'Dark Chocolate',
      'Heavy Cream',
      'Sugar',
      'Eggs',
      'Vanilla Extract',
    ],
    rating: 4.3,
    type: 'veg',
    image: '',
  },
  {
    name: 'Margherita Pasta',
    category: 'Pasta',
    price: 1099.99,
    ingredients: [
      'Penne Pasta',
      'Tomato Sauce',
      'Fresh Mozzarella',
      'Fresh Basil',
    ],
    rating: 4.6,
    type: 'veg',
    image: '',
  },
  {
    name: 'Hawaiian Pizza',
    category: 'Pizza',
    price: 1325.75,
    ingredients: [
      'Pizza Dough',
      'Tomato Sauce',
      'Mozzarella Cheese',
      'Ham',
      'Pineapple',
    ],
    rating: 4.2,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Chickpea Salad',
    category: 'Salad',
    price: 749.5,
    ingredients: [
      'Chickpeas',
      'Cherry Tomatoes',
      'Cucumber',
      'Red Onion',
      'Feta Cheese',
      'Balsamic Vinaigrette',
    ],
    rating: 4.4,
    type: 'veg',
    image: '',
  },
  {
    name: 'Paneer Tikka Masala',
    category: 'Indian',
    price: 1270.25,
    ingredients: [
      'Paneer',
      'Tomato-based Gravy',
      'Bell Peppers',
      'Onion',
      'Indian Spices',
    ],
    rating: 4.8,
    type: 'veg',
    image: '',
  },
  {
    name: 'Fish Tacos',
    category: 'Mexican',
    price: 1555.99,
    ingredients: [
      'Grilled Fish',
      'Corn Tortillas',
      'Cabbage Slaw',
      'Avocado',
      'Chipotle Mayo',
    ],
    rating: 4.7,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'Eggplant Parmesan',
    category: 'Italian',
    price: 1082.14,
    ingredients: [
      'Eggplant',
      'Marinara Sauce',
      'Mozzarella Cheese',
      'Parmesan Cheese',
      'Breadcrumbs',
    ],
    rating: 4.5,
    type: 'veg',
    image: '',
  },
  {
    name: 'Sushi Bowl',
    category: 'Asian',
    price: 1724.88,
    ingredients: [
      'Sushi Rice',
      'Raw Salmon',
      'Avocado',
      'Cucumber',
      'Soy Sauce',
    ],
    rating: 4.9,
    type: 'non-veg',
    image: '',
  },
  {
    name: 'BBQ Chicken Sandwich',
    category: 'Sandwich',
    price: 915.32,
    ingredients: ['BBQ Chicken', 'Coleslaw', 'Pickles', 'Brioche Bun'],
    rating: 4.3,
    type: 'non-veg',
    image: '',
  },
];
